<?php 
    /*CHALLENGE: 
     Each new term in the Fibonacci sequence is generated by adding the 
     previous two terms. By starting with 1 and 2, the first 10 terms will be:
            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
    */
    //Taken from: https://projecteuler.net/problem=2
    //Date: August 2, 2019


    $previous_number = 1;
    $last_number = 1;
    $sum = 0;
    $limit = 4000000;

    function is_even_valued_term(int $number_evaluated){ 
        if(($number_evaluated % 2) == 0){
            return true;
        }else{
            return false;
        }
    }

    while($last_number < $limit){
        $next_number = $previous_number + $last_number;
        $previous_number = $last_number;
        $last_number = $next_number;
        if(is_even_valued_term($next_number)){
            $sum = $sum + $next_number;
        }

    }
    echo $sum, PHP_EOL;
?>